MYSQL_HOST = "localhost"
MYSQL_USER = "root"
MYSQL_PASSWORD = "123456"
MYSQL_DATABASE = "py_jiuidankefang"
MYSQL_CHARSET = "utf8mb4"
MYSQL_PORT = 3306

SQLALCHEMY_DATABASE_URI = f'mysql+mysqldb://{MYSQL_USER}:{MYSQL_PASSWORD}@{MYSQL_HOST}:{MYSQL_PORT}/{MYSQL_DATABASE}?charset={MYSQL_CHARSET}'
SQLALCHEMY_TRACK_MODIFICATIONS = False
SECRET_KEY = 'hotel-knn-secret-key-2026'